//
// TODO : ENTETE ?
//

#ifndef LABO5_CHRONO_GENERATIONCHARACTEREALEATOIRE_H
#define LABO5_CHRONO_GENERATIONCHARACTEREALEATOIRE_H

char genererCharactereAleatoire(unsigned char begin, unsigned char end);

#endif //LABO5_CHRONO_GENERATIONCHARACTEREALEATOIRE_H
